### ISSUE TITLE
get_consensus_histories with question_id doesn't work

### ISSUE THREAD

**Issue by nlothian** [gfchallenge/gfc#6]
I'm the author of https://github.com/gfchallenge/gfc/pull/4

Thanks for applying it. But I'm not sure if something has changed at the backend, but it isn't working.

`gf.get_consensus_histories(created_after=datetime.datetime(2018,2,1,0,0,0),
                                  updated_before=datetime.datetime(2018,12,31))`
`[{u'answer_id': 511,
  u'consensus_at': u'2018-03-02T21:26:57.382Z',
  u'created_at': u'2018-03-02T21:26:58.350Z',
  u'decay_args': {u'percent': 0.468},
  u'decay_method': u'Aggregation::Decay::PercentRecent',
  u'id': 18,
  u'method_name': u'1-WeightedLogit-PercentRecent',
  u'normalized_value': 0.28251772,
  u'prediction_set_id': 6,
  u'question_id': 256,
  u'strategy': u'Aggregation::Strategies::Logit',
  u'updated_at': u'2018-03-02T23:30:12.313Z',
  u'value': 1.0,
  u'weighting_settings': {u'count_of_closed_questions_answered_requirement': 35,
   u'enabled': True,
   u'minimum_closed_questions_to_enable_accuracy_weighting': 10,
   u'percentage_of_closed_questions_answered_requirement': 0.5}},
...`

Note that the question_id is 256

Now if I call:

`gf.get_consensus_histories(question_id=256, created_after=datetime.datetime(2018,2,1,0,0,0),
                                  updated_before=datetime.datetime(2018,12,31)) `

I get

`[]`

What's wrong here? Happy to provide more details.

**Comment by danhorn** [comment]
Thanks for your contributions, and for asking the question about the question_id not returning any consensus histories. You've helped identify a bug in the back-end.  The issue has been identified and corrected. It will be tested and will be fixed when the next update is pushed on the back end.

**Comment by danhorn** [comment]
The back-end fix has been deployed.  Running the query using question_id should work properly.
